version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: integration-tests-slipstream
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example